name: Catenary
version: v0.7.0
output: build
require:
  - bolt
  - ps_beet_bolt.register.bolt_item
  - eroxified2

data_pack:
  description: "Adds hanging chains & ziplines!\nBy Eroxen."
  zipped: true
  min_format: [107, 1]
  max_format: 107
  load:
    - src

pipeline:
  - mecha
  - plugins.player_head_font
  - plugins.math_funcs
  - plugins.ratio_params
  - plugins.remove_empty_functions
  - beet.contrib.load

meta:
  load:
    data_pack:
      data: libs/*/data